language: go

before_install:
  # - curl -sf https://up.apex.sh/install | sudo sh
  # - pip install --user awscli
  # - export PATH=$PATH:$HOME/.local/bin
  # - aws configure set profile.${AWS_PROFILE_DEV}.aws_access_key_id $AWS_ACCOUNT_USER_ID_DEV
  # - aws configure set profile.${AWS_PROFILE_DEV}.aws_secret_access_key $AWS_ACCOUNT_SECRET_DEV
  # - aws configure set profile.${AWS_PROFILE_DEV}.region $AWS_DEFAULT_REGION

install:
  # - go get -t ./...
  # - sudo apt-get install jq -y

deploy:
  # dev
  - provider: script
    script: cd web && bash deploy.sh
    skip_cleanup: true
    on:
      branch: fix_lambda

env:
  - GO111MODULE=on
